spring.application.name=demo

# H2 persistente en archivo local (carpeta data/ del proyecto)
spring.datasource.url=jdbc:h2:file:./data/demo-db;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

